version: 0.2

phases:
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/stockexchange.jar
  discard-paths: yes